name: enhanced_meteorify
description: |
  Carefully extended meteorify package to interact with the Meteor framework.
  Connect your web or flutter apps, written in Dart, with the Meteor framework.
version: 1.0.0
homepage: https://github.com/wendellrocha/enhanced-meteorify
repository: https://github.com/wendellrocha/enhanced-meteorify

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  ddp: ^0.0.13
  mongo_dart: ^0.4.0

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
