name: enhanced_meteorify
description: |
  Carefully extended meteorify package to interact with the Meteor framework.
  Connect your web or flutter apps, written in Dart, with the Meteor framework.
version: 2.0.0-dev.2
homepage: https://github.com/wendellrocha/enhanced-meteorify
repository: https://github.com/wendellrocha/enhanced-meteorify

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  enhanced_ddp: ^1.0.10-dev.2
  shared_preferences: ^0.5.8
  crypto: ^2.1.5

dev_dependencies:
  pedantic: ^1.9.0